//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRandomNumber")]
public interface IRandomNumber
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomNumber/Next", ReplyAction="http://tempuri.org/IRandomNumber/NextResponse")]
    int Next();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomNumber/Next", ReplyAction="http://tempuri.org/IRandomNumber/NextResponse")]
    System.Threading.Tasks.Task<int> NextAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRandomNumberChannel : IRandomNumber, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RandomNumberClient : System.ServiceModel.ClientBase<IRandomNumber>, IRandomNumber
{
    
    public RandomNumberClient()
    {
    }
    
    public RandomNumberClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RandomNumberClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RandomNumberClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RandomNumberClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int Next()
    {
        return base.Channel.Next();
    }
    
    public System.Threading.Tasks.Task<int> NextAsync()
    {
        return base.Channel.NextAsync();
    }
}
