//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRandomNumber")]
public interface IRandomNumber
{
    
    // CODEGEN: Generating message contract since the wrapper name (RandomNumberRequest) of message RandomNumberRequest does not match the default value (Next)
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomNumber/Next", ReplyAction="http://tempuri.org/IRandomNumber/NextResponse")]
    RandomNumberResponse Next(RandomNumberRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomNumber/Next", ReplyAction="http://tempuri.org/IRandomNumber/NextResponse")]
    System.Threading.Tasks.Task<RandomNumberResponse> NextAsync(RandomNumberRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="RandomNumberRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class RandomNumberRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
    public int Max;
    
    public RandomNumberRequest()
    {
    }
    
    public RandomNumberRequest(int Max)
    {
        this.Max = Max;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="RandomNumberResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class RandomNumberResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public int Result;
    
    public RandomNumberResponse()
    {
    }
    
    public RandomNumberResponse(int Result)
    {
        this.Result = Result;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRandomNumberChannel : IRandomNumber, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RandomNumberClient : System.ServiceModel.ClientBase<IRandomNumber>, IRandomNumber
{
    
    public RandomNumberClient()
    {
    }
    
    public RandomNumberClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RandomNumberClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RandomNumberClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RandomNumberClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    RandomNumberResponse IRandomNumber.Next(RandomNumberRequest request)
    {
        return base.Channel.Next(request);
    }
    
    public int Next(int Max)
    {
        RandomNumberRequest inValue = new RandomNumberRequest();
        inValue.Max = Max;
        RandomNumberResponse retVal = ((IRandomNumber)(this)).Next(inValue);
        return retVal.Result;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<RandomNumberResponse> IRandomNumber.NextAsync(RandomNumberRequest request)
    {
        return base.Channel.NextAsync(request);
    }
    
    public System.Threading.Tasks.Task<RandomNumberResponse> NextAsync(int Max)
    {
        RandomNumberRequest inValue = new RandomNumberRequest();
        inValue.Max = Max;
        return ((IRandomNumber)(this)).NextAsync(inValue);
    }
}
